version: '3.7'

services:
  web:
    image: 192.168.4.50:5000/aliexpress:latest
    restart: always
    build: 
      context: ./aliexpress_scraper
      dockerfile: Dockerfile.prod
    command: gunicorn aliexpress_scraper.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.prod.db
  nginx:
    image: 192.168.4.50:5000/aliexpress_nginx:latest
    build: ./nginx
    restart: always
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
