version: '3.7'

services:
  web:
    build: ./aliexpress_scraper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./aliexpress_scraper/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=scraper
      - POSTGRES_DB=aliexpress_scraper

volumes:
  postgres_data: