# Generated by Django 3.0.3 on 2020-05-10 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ltltlt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 20, 36, 56, 519190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='price',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 20, 36, 56, 519190, tzinfo=utc), verbose_name='Date Scraped'),
        ),
    ]
