# Generated by Django 3.0.3 on 2020-05-11 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ltltlt', '0002_auto_20200510_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='price',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Scraped'),
        ),
    ]
