# Generated by Django 3.0.3 on 2020-05-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltltlt', '0003_auto_20200510_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'get_latest_by': ['datetime'], 'ordering': ['datetime']},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(max_length=20),
        ),
    ]
